/*PROCEDIMIENTOS ALMACENADOS*/

use db_clinica_eylinlopez;

/*INSERT*/

DELIMITER $$

--
-- Procedimientos
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_ADD_IMAGEN` (IN `IMAGEN` VARCHAR(30), IN `OBSERVACIONES` VARCHAR(30))  BEGIN
START TRANSACTION;
SELECT @COD_IMAGEN := MAX(COD_IMAGEN)+1 FROM tbl_galeria;
INSERT INTO `tbl_galeria`(`COD_IMAGEN`, `IMAGEN`, `OBSERVACIONES`) VALUES (@COD_IMAGEN,IMAGEN,OBSERVACIONES);
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_AÑADIR_ACTUALIZAR_CONSULTA` (IN `COD_CONSULTA` INT, IN `COD_PACIENTE` INT, IN `TIPO_CONSULTA` VARCHAR(30), IN `LUGAR` VARCHAR(30), IN `SEGURO_MEDICO` VARCHAR(30), IN `ASEGURADORA` VARCHAR(30), IN `POLIZA_RELACION` VARCHAR(30), IN `COD_SIGNOS` INT, IN `COD_DIAGNOSTICO` INT, IN `COD_EXAMEN` INT, IN `COD_TRATAMIENTO` INT, IN `COD_ANT_OBSTETRICOS` INT, IN `COD_ANT_PATOLOGICO` INT, IN `COD_IIMAGEN` INT, IN `COD_FACTURA` INT, IN `FECHA_REGISTRO` DATETIME)  BEGIN
START TRANSACTION;
UPDATE `tbl_consultas` SET `COD_PACIENTE`=COD_PACIENTE,`TIPO_CONSULTA`=TIPO_CONSULTA,
`LUGAR`=LUGAR,`SEGURO_MEDICO`=SEGURO_MEDICO,
`ASEGURADORA`=ASEGURADORA,
`RELACION_POLIZA`=POLIZA_RELACION
,`COD_SIGNOS`=COD_SIGNOS,
`COD_DIAGNOSTICO`=COD_DIAGNOSTICO,
`COD_EXAMEN`=COD_EXAMEN,
`COD_TRATAMIENTO`=COD_TRATAMIENTO,
`COD_ANT_OBSTETRICOS`=COD_ANT_OBSTETRICOS
,`COD_ANT_PATOLOGICO`=COD_ANT_PATOLOGICO,
`COD_IIMAGEN`=COD_IIMAGEN,
`COD_FACTURA`=COD_FACTURA,
`FECHA_REGISTRO`=FECHA_REGISTRO
WHERE tbl_consultas.COD_CONSULTA=COD_CONSULTA;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DELETE_CITA` (IN `COD_CITA` INT(11))  BEGIN
  START TRANSACTION;
   DELETE FROM TBL_CITAS WHERE TBL_CITAS.COD_CITA=COD_CITA; 
   COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DELETE_CLINICA` (IN `COD_CLINICA` INT(11))  BEGIN
  START TRANSACTION;
  DELETE FROM TBL_CLINICA WHERE TBL_CLINICA.COD_CLINICA=COD_CLINICA;
  COMMIT;
END$$


CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DELETE_CONSULTA_PACIENTE` (IN `COD_CONSULTA` INT)  BEGIN
START TRANSACTION;
SELECT @COD_PACIENTE := tbl_pacientes.COD_PACIENTE,
@COD_CONSULTA := tbl_consultas.COD_CONSULTA,
@COD_SIGNOS := tbl_signos_vitales.COD_SIGNOS,
@COD_DIAGNOSTICO := tbl_diagnosticos.COD_DIAGNOSTICO,
@COD_EXAMEN := tbl_examenes.COD_EXAMEN,
@COD_TRATAMIENTO := tbl_tratamientos.COD_TRATAMIENTO,
@COD_ANT_OBSTETRICOS := tbl_ant_obstetricos.COD_ANT_OBSTETRICOS,
@COD_ANT_PATOLOGICO := tbl_ant_patologicos.COD_ANT_PATOLOGICO,
@COD_IMAGEN := tbl_galeria.COD_IMAGEN,
@COD_FACTURA := tbl_facturas.COD_FACTURA
FROM 
tbl_consultas INNER JOIN 
tbl_pacientes INNER JOIN 
tbl_signos_vitales INNER JOIN 
tbl_diagnosticos INNER JOIN
tbl_examenes INNER JOIN
tbl_tratamientos INNER JOIN
tbl_ant_obstetricos INNER JOIN
tbl_ant_patologicos INNER JOIN
tbl_galeria INNER JOIN
tbl_facturas 
WHERE 
tbl_consultas.COD_CONSULTA=COD_CONSULTA AND
tbl_pacientes.COD_PACIENTE= tbl_consultas.COD_PACIENTE AND
tbl_signos_vitales.COD_SIGNOS=tbl_consultas.COD_SIGNOS AND
tbl_diagnosticos.COD_DIAGNOSTICO= tbl_consultas.COD_DIAGNOSTICO AND
tbl_examenes.COD_EXAMEN=tbl_consultas.COD_EXAMEN AND
tbl_tratamientos.COD_TRATAMIENTO=tbl_consultas.COD_TRATAMIENTO AND tbl_ant_obstetricos.COD_ANT_OBSTETRICOS=tbl_consultas.COD_ANT_OBSTETRICOS AND tbl_ant_patologicos.COD_ANT_PATOLOGICO=tbl_consultas.COD_ANT_PATOLOGICO AND tbl_galeria.COD_IMAGEN= tbl_consultas.COD_IIMAGEN AND tbl_facturas.COD_FACTURA = tbl_consultas.COD_FACTURA;
DELETE  FROM tbl_consultas 
WHERE tbl_consultas.COD_CONSULTA= @COD_CONSULTA;
DELETE  FROM tbl_signos_vitales 
WHERE tbl_signos_vitales.COD_SIGNOS= @COD_SIGNOS;
DELETE  FROM tbl_diagnosticos 
WHERE tbl_diagnosticos.COD_DIAGNOSTICO= @COD_DIAGNOSTICO;
DELETE  FROM tbl_tratamientos
WHERE tbl_tratamientos.COD_TRATAMIENTO= @COD_TRATAMIENTO;
DELETE  FROM tbl_galeria
WHERE tbl_galeria.COD_IMAGEN= @COD_IMAGEN;
DELETE  FROM tbl_facturas
WHERE tbl_facturas.COD_FACTURA= @COD_FACTURA;
DELETE  FROM tbl_examenes
WHERE tbl_examenes.COD_EXAMEN= @COD_EXAMEN;
DELETE  FROM tbl_ant_patologicos
WHERE tbl_ant_patologicos.COD_ANT_PATOLOGICO= @COD_ANT_PATOLOGICO;
DELETE  FROM tbl_ant_obstetricos
WHERE tbl_ant_obstetricos.COD_ANT_OBSTETRICOS= @COD_ANT_OBSTETRICOS;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DELETE_PACIENTE_ENCARGADO` (IN `COD_PACIENTE` INT(11))  BEGIN

DELETE FROM tbl_citas where tbl_citas.COD_PACIENTE = COD_PACIENTE;
DELETE FROM tbl_consultas where tbl_consultas.COD_PACIENTE = COD_PACIENTE;
SELECT @COD_ENCARGADO :=COD_ENCARGADO FROM tbl_pacientes WHERE tbl_pacientes.COD_PACIENTE = COD_PACIENTE;
DELETE FROM tbl_pacientes where tbl_pacientes.COD_PACIENTE = COD_PACIENTE;
DELETE FROM tbl_encargado where tbl_encargado.COD_ENCARGADO = @COD_ENCARGADO;

END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DELETE_TRATAMIENTO` (IN `COD_TRATAMIENTO` INT)  DELETE FROM `tbl_tratamientos` WHERE tbl_tratamientos.COD_TRATAMIENTO= COD_TRATAMIENTO$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DELETE_USUARIO` (IN `COD_USUARIO` INT(10))  DELETE FROM `tbl_usuarios` WHERE tbl_usuarios.COD_USUARIO=COD_USUARIO$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_CITA` (IN `PRI_NOMBRE` VARCHAR(30), IN `ASUNTO_NOMBRE` VARCHAR(20), IN `LUGAR_CLINICA` VARCHAR(30), IN `FECHA_INICIO` DATETIME, IN `FECHA_FIN` DATETIME, IN `ESTADO_CITA` VARCHAR(2), IN `FECHA_REGISTRO` DATE)  BEGIN
START TRANSACTION;
SELECT @COD_PACIENTE := COD_PACIENTE FROM tbl_pacientes WHERE tbl_pacientes.PRI_NOMBRE=PRI_NOMBRE;

INSERT INTO `tbl_citas`(`COD_CITA`, `COD_PACIENTE`, `ASUNTO_NOMBRE`, `LUGAR_CLINICA`, `FECHA_INICIO`, `FECHA_FIN`, `ESTADO_CITA`, `FECHA_REGISTRO`) VALUES (COD_CITA,@COD_PACIENTE,ASUNTO_NOMBRE,LUGAR_CLINICA,FECHA_INICIO,FECHA_FIN,ESTADO_CITA,FECHA_REGISTRO);

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_CLINICA` (IN `NOM_CLINICA` VARCHAR(20), IN `HORARIO_CLINICA` VARCHAR(20), IN `TELEFONO_CLINICA` VARCHAR(15), IN `UBICACION_CLI` VARCHAR(40), IN `RTN_CLINICA` VARCHAR(20), IN `RED_SOCIAL` VARCHAR(11), IN `LOGO_CLINICA` VARCHAR(20), IN `FECHA_REGISTRO` DATETIME, IN `NOMBRE_CAI` VARCHAR(20), IN `FECHA_INICIAL` DATETIME, IN `FECHA_FINAL` DATETIME, IN `RAN_INICIAL` INT, IN `RAN_FINAL` INT, IN `ESTADO_CAI` INT)  BEGIN
START TRANSACTION;

INSERT INTO `tbl_leg_tributaria`(`COD_CAI`, `NOMBRE_CAI`, `FECHA_INICIAL`, `FECHA_FINAL`, `RAN_INICIAL`, `RAN_FINAL`, `ESTADO_CAI`) VALUES (COD_CAI,NOMBRE_CAI,FECHA_INICIAL,FECHA_FINAL,RAN_INICIAL,RAN_FINAL,ESTADO_CAI);
/************************/
SELECT @COD_CAI :=MAX(COD_CAI) FROM tbl_leg_tributaria;
/***********/

INSERT INTO `tbl_clinica`(`COD_CLINICA`, `NOM_CLINICA`, `HORARIO_CLINICA`, `TELEFONO_CLINICA`, `UBICACION_CLI`, `RTN_CLINICA`, `RED_SOCIAL`, `LOGO_CLINICA`, `COD_CAI`, `FECHA_REGISTRO`) VALUES (COD_CLINICA,NOM_CLINICA,HORARIO_CLINICA,TELEFONO_CLINICA,UBICACION_CLI,RTN_CLINICA,RED_SOCIAL
,LOGO_CLINICA,@COD_CAI,FECHA_REGISTRO);
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_CONSULTA` (IN `COD_PACIENTE` INT(11), IN `TIPO_CONSULTA` VARCHAR(30), IN `LUGAR` VARCHAR(30), IN `SEGURO_MEDICO` VARCHAR(2), IN `ASEGURADORA` VARCHAR(30), IN `RELACION_POLIZA` VARCHAR(30), IN `ESTATURA` VARCHAR(20), IN `SATO2` VARCHAR(20), IN `PESO` VARCHAR(20), IN `TEMPERATURA` VARCHAR(20), IN `PRESIÓN_ALTERIAL` VARCHAR(20), IN `FRECUENCIA_CARDIACA` VARCHAR(20), IN `FRECUENCIA_RESPIRATORIA` VARCHAR(20), IN `NOTAS` VARCHAR(50), IN `DESCRIPCION_SIGNOS` VARCHAR(100), IN `FECHA_REGISTRO_SIGNOS` VARCHAR(30), IN `CIE` VARCHAR(30), IN `NOMBRE_DIAGNOSTICO` VARCHAR(50), IN `EQUIVALENCIAS` VARCHAR(30), IN `DESCRIPCION_DIAGNOSTICO` VARCHAR(50), IN `NOMBRE_EXAMEN` VARCHAR(30), IN `ETIQUETAS_EXAMEN` VARCHAR(30), IN `CODIGO_EXAMEN` VARCHAR(30), IN `MEDICAMENTO` VARCHAR(30), IN `MARCA_MEDICAMENTO` VARCHAR(30), IN `CANTIDAD_MEDICAMENTO` TINYINT(4), IN `DOSIS_INDICACIONES` VARCHAR(30), IN `DESCRIPCION_MEDICAMENTO` VARCHAR(30), IN `MENARQUIA` VARCHAR(20), IN `EMBARAZOS` VARCHAR(20), IN `PLANIFICACION` VARCHAR(20), IN `PERIODO_MESTRUAL` VARCHAR(20), IN `FECHA_ULTIMA_MESTRU` VARCHAR(30), IN `ANTECEDENTE_PATOLOGICO` VARCHAR(30), IN `ALERGIAS` VARCHAR(30), IN `HABITOS` VARCHAR(30), IN `CONSUMO_MEDICAMENTO` VARCHAR(30), IN `TIPO_ANTECEDENTE` VARCHAR(30), IN `ENFERMEDAD_PATOLOGICA` VARCHAR(30), IN `IMAGEN` VARCHAR(30), IN `OBSERVACIONES_IMAGEN` VARCHAR(30), IN `SUB_TOTAL_FACTURA` DECIMAL, IN `IMPUESTO` DECIMAL, IN `TOTAL_FACTURA` DECIMAL, IN `DESCRIPCION_FACTURA` VARCHAR(30))  BEGIN
START TRANSACTION;

INSERT INTO `tbl_signos_vitales`(`COD_SIGNOS`, `ESTATURA`, `SATO2`, `PESO`, `TEMPERATURA`, `PRESIÓN_ALTERIAL`, `FRECUENCIA_CARDIACA`, `FRECUENCIA_RESPIRATORIA`, `NOTAS`, `DESCRIPCION`, `FECHA_REGISTRO`) VALUES (COD_SIGNOS, ESTATURA,SATO2, PESO, TEMPERATURA, PRESIÓN_ALTERIAL,FRECUENCIA_CARDIACA,FRECUENCIA_RESPIRATORIA, NOTAS,DESCRIPCION_SIGNOS, FECHA_REGISTRO_SIGNOS);
/********/
SELECT @COD_SIGNOS := MAX(COD_SIGNOS) FROM tbl_signos_vitales ;
/********/
INSERT INTO `tbl_diagnosticos`(`COD_DIAGNOSTICO`, `CIE`, `NOMBRE_DIAGNOSTICO`, `EQUIVALENCIAS`, `DESCRIPCION`) VALUES (COD_DIAGNOSTICO, CIE, NOMBRE_DIAGNOSTICO, EQUIVALENCIAS, DESCRIPCION_DIAGNOSTICO);
/*********/
SELECT @COD_DIAGNOSTICO := MAX(COD_DIAGNOSTICO) FROM tbl_diagnosticos;
/********/
INSERT INTO `tbl_examenes`(`COD_EXAMEN`, `NOMBRE_EXAMEN`, `ETIQUETAS`, `CODIGO`) VALUES (COD_EXAMEN, NOMBRE_EXAMEN, ETIQUETAS_EXAMEN,CODIGO_EXAMEN);
/********/
SELECT @COD_EXAMEN := MAX(COD_EXAMEN) FROM tbl_examenes;
/*******/
INSERT INTO `tbl_tratamientos`(`COD_TRATAMIENTO`, `MEDICAMENTO`, `MARCA`, `CANTIDAD`, `DOSIS_INDICACIONES`, `DESCRIPCION`) VALUES (COD_TRATAMIENTO, MEDICAMENTO,MARCA_MEDICAMENTO, CANTIDAD_MEDICAMENTO, DOSIS_INDICACIONES,DESCRIPCION_MEDICAMENTO);
/**********/
SELECT @COD_TRATAMIENTO :=MAX(COD_TRATAMIENTO)  FROM tbl_tratamientos;
/*********/
INSERT INTO `tbl_ant_obstetricos`(`COD_ANT_OBSTETRICOS`, `MENARQUIA`, `EMABARAZOS`, `PLANIFICACION`, `PERIODO_MESTRUAL`, `FECHA_ULTIMA_MESTRU`) VALUES (COD_ANT_OBSTETRICOS, MENARQUIA,EMBARAZOS, PLANIFICACION, PERIODO_MESTRUAL, FECHA_ULTIMA_MESTRU);
/******/
SELECT @COD_ANT_OBSTETRICOS := MAX(COD_ANT_OBSTETRICOS) FROM tbl_ant_obstetricos;
/*************/
INSERT INTO `tbl_ant_patologicos`(`COD_ANT_PATOLOGICO`, `ANT_PATOLOGICO`, `TIPO_ANTECEDENTE`, `ENFERMEDAD`,`ALERGIAS`,`HABITOS`,`CONSUMO_MEDICAMENTO`) VALUES (COD_ANT_PATOLOGICO,ANTECEDENTE_PATOLOGICO, TIPO_ANTECEDENTE, ENFERMEDAD_PATOLOGICA,ALERGIAS,HABITOS,CONSUMO_MEDICAMENTO);
/************/
SELECT @COD_ANT_PATOLOGICO := MAX(COD_ANT_PATOLOGICO) FROM tbl_ant_patologicos;
/*************/
INSERT INTO `tbl_galeria`(`COD_IMAGEN`, `IMAGEN`, `OBSERVACIONES`) VALUES (COD_IMAGEN, IMAGEN, OBSERVACIONES_IMAGEN);
/******/
SELECT @COD_IMAGEN:= MAX(COD_IMAGEN) FROM tbl_galeria;
/***************/
INSERT INTO `tbl_facturas`(`COD_FACTURA`, `SUB_TOTAL`, `IMPUESTO`, `TOTAL`, `DESCRIPCION`) VALUES (COD_FACTURA, SUB_TOTAL_FACTURA, IMPUESTO, TOTAL_FACTURA, DESCRIPCION_FACTURA);
/****************/
SELECT @COD_FACTURA := MAX(COD_FACTURA) FROM tbl_facturas;
/**********/
INSERT INTO `tbl_consultas`(`COD_CONSULTA`, `COD_PACIENTE`, `TIPO_CONSULTA`, `LUGAR`, `SEGURO_MEDICO`, `ASEGURADORA`, `RELACION_POLIZA`, `COD_SIGNOS`, `COD_DIAGNOSTICO`, `COD_EXAMEN`, `COD_TRATAMIENTO`, `COD_ANT_OBSTETRICOS`, `COD_ANT_PATOLOGICO`, `COD_IIMAGEN`, `COD_FACTURA`, `FECHA_REGISTRO`) VALUES (@COD_CONSULTA,COD_PACIENTE, TIPO_CONSULTA, LUGAR, SEGURO_MEDICO, ASEGURADORA, RELACION_POLIZA, @COD_SIGNOS, @COD_DIAGNOSTICO,@COD_EXAMEN,@COD_TRATAMIENTO, @COD_ANT_OBSTETRICOS,@COD_ANT_PATOLOGICO, @COD_IMAGEN, @COD_FACTURA, FECHA_REGISTRO_SIGNOS);
/**************************/


COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_IMAGEN_PACIENTE` (IN `COD_PACIENTE` INT, IN `IMAGEN` VARCHAR(30), IN `OBSERVACIONES_IMAGEN` VARCHAR(30))  BEGIN
START TRANSACTION;

/********/
SELECT @COD_SIGNOS := MAX(COD_SIGNOS) FROM tbl_signos_vitales ;
/********/

/*********/
SELECT @COD_DIAGNOSTICO := MAX(COD_DIAGNOSTICO) FROM tbl_diagnosticos;
/********/

/********/
SELECT @COD_EXAMEN := MAX(COD_EXAMEN) FROM tbl_examenes;
/*******/

/**********/
SELECT @COD_TRATAMIENTO :=MAX(COD_TRATAMIENTO)  FROM tbl_tratamientos;
/*********/

/******/
SELECT @COD_ANT_OBSTETRICOS := MAX(COD_ANT_OBSTETRICOS) FROM tbl_ant_obstetricos;
/*************/

/************/
SELECT @COD_ANT_PATOLOGICO := MAX(COD_ANT_PATOLOGICO) FROM tbl_ant_patologicos;
/*************/
INSERT INTO `tbl_galeria`(`COD_IMAGEN`, `IMAGEN`, `OBSERVACIONES`) VALUES (COD_IMAGEN, IMAGEN, OBSERVACIONES_IMAGEN);
/******/
SELECT @COD_IMAGEN:= MAX(COD_IMAGEN) FROM tbl_galeria;
/***************/
/****************/
SELECT @COD_FACTURA := MAX(COD_FACTURA) FROM tbl_facturas;
/**********/
INSERT INTO `tbl_consultas`(`COD_CONSULTA`, `COD_PACIENTE`, `TIPO_CONSULTA`, `LUGAR`, `SEGURO_MEDICO`, `ASEGURADORA`, `RELACION_POLIZA`, `COD_SIGNOS`, `COD_DIAGNOSTICO`, `COD_EXAMEN`, `COD_TRATAMIENTO`, `COD_ANT_OBSTETRICOS`, `COD_ANT_PATOLOGICO`, `COD_IIMAGEN`, `COD_FACTURA`, `FECHA_REGISTRO`) VALUES (@COD_CONSULTA,COD_PACIENTE, TIPO_CONSULTA, LUGAR, SEGURO_MEDICO, ASEGURADORA, RELACION_POLIZA, @COD_SIGNOS, @COD_DIAGNOSTICO,@COD_EXAMEN,@COD_TRATAMIENTO, @COD_ANT_OBSTETRICOS,@COD_ANT_PATOLOGICO, @COD_IMAGEN, @COD_FACTURA, FECHA_REGISTRO);
/**************************/


COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_PACIENTE_ENCARGADO_DEPARTAMENTO` (IN `PRI_NOMBRE` VARCHAR(30), IN `SEG_NOMBRE` VARCHAR(30), IN `PRI_APELLIDO` VARCHAR(30), IN `SEG_APELLIDO` VARCHAR(30), IN `GENERO` VARCHAR(30), IN `FECHA_NACIMIENTO` DATE, IN `EDAD` TINYINT(4), IN `TIPO_ID` VARCHAR(30), IN `NUMERO_ID` VARCHAR(30), IN `ACTIVO_INACTIVO` VARCHAR(30), IN `CORREO` VARCHAR(40), IN `TELEFONO_PAC` VARCHAR(30), IN `DIRECCION` VARCHAR(100), IN `DEPARTAMENTO` VARCHAR(30), IN `IDENTIFICACION` VARCHAR(30), IN `NOM_ENCARGADO` VARCHAR(30), IN `TELEFONO` VARCHAR(30), IN `PARENTESCO` VARCHAR(30))  BEGIN
START TRANSACTION;
INSERT INTO `tbl_encargado`( `NOM_ENCARGADO`, `PARENTESCO`, `IDENTIFICACION`, `TELEFONO`) VALUES (NOM_ENCARGADO,PARENTESCO,IDENTIFICACION,TELEFONO);
/********************/
SELECT @COD_ENCARGADO :=MAX(COD_ENCARGADO) FROM tbl_encargado;
SELECT @COD_DEPARTAMENTO := COD_DEPARTAMENTO FROM tbl_departamentos WHERE tbl_departamentos.DEPARTAMENTO =DEPARTAMENTO;
/********************/
INSERT INTO `tbl_pacientes`(`PRI_NOMBRE`, `SEG_NOMBRE`, `PRI_APELLIDO`, `SEG_APELLIDO`, `GENERO`, `FECHA_NACIMIENTO`, `EDAD`, `TIPO_ID`, `NUMERO_ID`, `ACTIVO_INACTIVO`, `CORREO`, `TELEFONO`, `DIRECCION`, `COD_DEPARTAMENTO`, `COD_ENCARGADO`, `FECHA_REGISTRO`) VALUES (PRI_NOMBRE,SEG_NOMBRE,PRI_APELLIDO,SEG_APELLIDO,GENERO,FECHA_NACIMIENTO,EDAD,TIPO_ID,NUMERO_ID,ACTIVO_INACTIVO
,CORREO,TELEFONO_PAC,DIRECCION,@COD_DEPARTAMENTO,@COD_ENCARGADO,current_timestamp());
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_SEGUIMIENTO_SIGNOS_VITALES` (IN `COD_PACIENTE` INT, IN `ESTATURA` VARCHAR(30), IN `SATO2` VARCHAR(30), IN `PESO` VARCHAR(30), IN `TEMPERATURA` VARCHAR(30), IN `PRESIÓN_ALTERIAL` VARCHAR(30), IN `FRECUENCIA_CARDIACA` VARCHAR(30), IN `FRECUENCIA_RESPIRATORIA` VARCHAR(30), IN `NOTAS` VARCHAR(30), IN `DESCRIPCION_SIGNOS` VARCHAR(30), IN `FECHA_REGISTRO_SIGNOS` DATETIME)  BEGIN
START TRANSACTION;

INSERT INTO `tbl_signos_vitales`(`COD_SIGNOS`, `ESTATURA`, `SATO2`, `PESO`, `TEMPERATURA`, `PRESIÓN_ALTERIAL`, `FRECUENCIA_CARDIACA`, `FRECUENCIA_RESPIRATORIA`, `NOTAS`, `DESCRIPCION`, `FECHA_REGISTRO`) VALUES (COD_SIGNOS, ESTATURA,SATO2, PESO, TEMPERATURA, PRESIÓN_ALTERIAL,FRECUENCIA_CARDIACA,FRECUENCIA_RESPIRATORIA, NOTAS,DESCRIPCION_SIGNOS,FECHA_REGISTRO_SIGNOS);
/********/
SELECT @COD_SIGNOS := MAX(COD_SIGNOS) FROM tbl_signos_vitales ;
/********/

/*********/
SELECT @COD_DIAGNOSTICO := MAX(COD_DIAGNOSTICO) FROM tbl_diagnosticos;
/********/

/********/
SELECT @COD_EXAMEN := MAX(COD_EXAMEN) FROM tbl_examenes;
/*******/

/**********/
SELECT @COD_TRATAMIENTO :=MAX(COD_TRATAMIENTO)  FROM tbl_tratamientos;
/*********/
/******/
SELECT @COD_ANT_OBSTETRICOS := MAX(COD_ANT_OBSTETRICOS) FROM tbl_ant_obstetricos;
/*************/
/************/
SELECT @COD_ANT_PATOLOGICO := MAX(COD_ANT_PATOLOGICO) FROM tbl_ant_patologicos;
/*************/
/******/
SELECT @COD_IMAGEN:= MAX(COD_IMAGEN) FROM tbl_galeria;
/***************/
/****************/
SELECT @COD_FACTURA := MAX(COD_FACTURA) FROM tbl_facturas;
/**********/
INSERT INTO `tbl_consultas`(`COD_CONSULTA`, `COD_PACIENTE`, `TIPO_CONSULTA`, `LUGAR`, `SEGURO_MEDICO`, `ASEGURADORA`, `RELACION_POLIZA`, `COD_SIGNOS`, `COD_DIAGNOSTICO`, `COD_EXAMEN`, `COD_TRATAMIENTO`, `COD_ANT_OBSTETRICOS`, `COD_ANT_PATOLOGICO`, `COD_IIMAGEN`, `COD_FACTURA`, `FECHA_REGISTRO`) VALUES (@COD_CONSULTA,COD_PACIENTE,'', '', '', '', '', @COD_SIGNOS,'','','', '','', '', '','');
/**************************/


COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_USUARIO` (IN `NOM_USUARIO` VARCHAR(20), IN `TIPO_USUARIO` VARCHAR(20), IN `CONTRASEÑA` VARCHAR(20), IN `CORREO` VARCHAR(30), IN `FECHA_REGISTRO` DATETIME)  BEGIN
START TRANSACTION;
INSERT INTO `tbl_usuarios`(`COD_USUARIO`, `NOM_USUARIO`, `TIPO_USUARIO`, `CONTRASEÑA`, `CORREO`, `FECHA_REGISTRO`) VALUES (COD_USUARIO,NOM_USUARIO,TIPO_USUARIO, CONTRASEÑA,CORREO,FECHA_REGISTRO);
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_CITA` (IN `COD_CITA` INT(11))  BEGIN
START TRANSACTION;

SELECT concat(p.PRI_NOMBRE, ' ' ,p.PRI_APELLIDO) as Nombre,c.ASUNTO_NOMBRE,p.TELEFONO,c.LUGAR_CLINICA,
c.FECHA_INICIO,c.FECHA_FIN,c.ESTADO_CITA,c.FECHA_REGISTRO
FROM tbl_citas c, tbl_pacientes p
where c.COD_CITA = COD_CITA
and c.COD_PACIENTE = p.COD_PACIENTE;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_CITAS` ()  BEGIN
START TRANSACTION;
SELECT `COD_CITA`, `COD_PACIENTE`, `ASUNTO_NOMBRE`, `LUGAR_CLINICA`, `FECHA_INICIO`, `FECHA_FIN`, `ESTADO_CITA`, `FECHA_REGISTRO` FROM `tbl_citas`; 
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_CITA_PACIENTE` (IN `COD_PACIENTE` INT(11))  BEGIN
START TRANSACTION;
SELECT concat(p.PRI_NOMBRE, ' ', p.SEG_NOMBRE,' ',p.PRI_APELLIDO,' ',p.SEG_APELLIDO) as Nombre,p.NUMERO_ID,c.ASUNTO_NOMBRE,p.TELEFONO,c.LUGAR_CLINICA,
c.FECHA_INICIO,c.FECHA_FIN,c.ESTADO_CITA,c.FECHA_REGISTRO
FROM tbl_pacientes p ,tbl_citas c
where c.COD_PACIENTE = COD_PACIENTE
AND p.COD_PACIENTE = c.COD_PACIENTE;  
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_CITA_RANGO_FECHA` (IN `FECHA_DESDE` DATETIME, IN `FECHA_HASTA` DATETIME)  BEGIN

START TRANSACTION;
 SELECT c.COD_CITA, concat(p.PRI_NOMBRE, ' ', p.SEG_NOMBRE,' ',p.PRI_APELLIDO,' ',p.SEG_APELLIDO) as Nombre ,p.NUMERO_ID,p.TELEFONO,c.FECHA_INICIO,c.FECHA_FIN,c.ESTADO_CITA
 FROM tbl_citas c, tbl_pacientes p
 where convert(c.FECHA_INICIO, date) between FECHA_DESDE AND FECHA_HASTA
 and c.COD_PACIENTE = p.COD_PACIENTE;
COMMIT;
END$$

CREATE DEFINER=`sayronv`@`localhost` PROCEDURE `SP_SELECT_CLIN_CODIGO` (IN `COD_CLINICA` INT(11))  SELECT * FROM `tbl_clinica` where tbl_clinica.COD_CLINICA= COD_CLINICA$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_EXPEDIENTES` ()  BEGIN
START TRANSACTION;

SELECT tbl_consultas.COD_CONSULTA, tbl_pacientes.PRI_NOMBRE,tbl_pacientes.SEG_NOMBRE,tbl_pacientes.EDAD,tbl_pacientes.GENERO,tbl_consultas.TIPO_CONSULTA,
tbl_signos_vitales.ESTATURA,tbl_signos_vitales.SATO2,tbl_signos_vitales.PESO,
tbl_signos_vitales.TEMPERATURA,tbl_signos_vitales.PRESIÓN_ALTERIAL,tbl_signos_vitales.FRECUENCIA_CARDIACA,
tbl_signos_vitales.FRECUENCIA_RESPIRATORIA,tbl_diagnosticos.CIE,tbl_diagnosticos.NOMBRE_DIAGNOSTICO,
tbl_examenes.NOMBRE_EXAMEN,tbl_tratamientos.MEDICAMENTO,tbl_tratamientos.MARCA,
tbl_ant_obstetricos.MENARQUIA , tbl_ant_obstetricos.EMABARAZOS,tbl_ant_obstetricos.PLANIFICACION,tbl_ant_obstetricos.FECHA_ULTIMA_MESTRU,
tbl_ant_patologicos.ANT_PATOLOGICO,tbl_ant_patologicos.TIPO_ANTECEDENTE,tbl_ant_patologicos.ENFERMEDAD,tbl_ant_patologicos.ALERGIAS,
tbl_ant_patologicos.HABITOS,tbl_ant_patologicos.CONSUMO_MEDICAMENTO,tbl_galeria.IMAGEN,tbl_galeria.OBSERVACIONES,
tbl_facturas.TOTAL,tbl_signos_vitales.FECHA_REGISTRO

FROM 
tbl_consultas INNER JOIN 
tbl_pacientes INNER JOIN 
tbl_signos_vitales INNER JOIN 
tbl_diagnosticos INNER JOIN
tbl_examenes INNER JOIN
tbl_tratamientos INNER JOIN
tbl_ant_obstetricos INNER JOIN
tbl_ant_patologicos INNER JOIN
tbl_galeria INNER JOIN
tbl_facturas 

WHERE 
tbl_pacientes.COD_PACIENTE =tbl_pacientes.COD_PACIENTE AND
tbl_pacientes.COD_PACIENTE= tbl_consultas.COD_PACIENTE AND
tbl_signos_vitales.COD_SIGNOS=tbl_consultas.COD_SIGNOS AND
tbl_diagnosticos.COD_DIAGNOSTICO= tbl_consultas.COD_DIAGNOSTICO AND
tbl_examenes.COD_EXAMEN=tbl_consultas.COD_EXAMEN AND
tbl_tratamientos.COD_TRATAMIENTO=tbl_consultas.COD_TRATAMIENTO AND tbl_ant_obstetricos.COD_ANT_OBSTETRICOS=tbl_consultas.COD_ANT_OBSTETRICOS AND
tbl_ant_patologicos.COD_ANT_PATOLOGICO=tbl_consultas.COD_ANT_PATOLOGICO AND
tbl_galeria.COD_IMAGEN= tbl_consultas.COD_IIMAGEN AND
tbl_facturas.COD_FACTURA = tbl_consultas.COD_FACTURA;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_EXPEDIENTE_PACIENTE` (IN `COD_CONSULTA` INT)  BEGIN
START TRANSACTION;

SELECT tbl_consultas.COD_CONSULTA, tbl_pacientes.PRI_NOMBRE,tbl_pacientes.SEG_NOMBRE,tbl_pacientes.EDAD,tbl_pacientes.GENERO,tbl_consultas.TIPO_CONSULTA,
tbl_signos_vitales.ESTATURA,tbl_signos_vitales.SATO2,tbl_signos_vitales.PESO,
tbl_signos_vitales.TEMPERATURA,tbl_signos_vitales.PRESIÓN_ALTERIAL,tbl_signos_vitales.FRECUENCIA_CARDIACA,
tbl_signos_vitales.FRECUENCIA_RESPIRATORIA,tbl_signos_vitales.NOTAS,tbl_signos_vitales.DESCRIPCION,tbl_signos_vitales.FECHA_REGISTRO,tbl_diagnosticos.CIE,tbl_diagnosticos.NOMBRE_DIAGNOSTICO,
tbl_examenes.NOMBRE_EXAMEN,tbl_examenes.ETIQUETAS,tbl_examenes.CODIGO,tbl_tratamientos.CANTIDAD,tbl_tratamientos.DOSIS_INDICACIONES,tbl_tratamientos.DESCRIPCION,tbl_tratamientos.MEDICAMENTO,tbl_tratamientos.MARCA,
tbl_ant_obstetricos.MENARQUIA , tbl_ant_obstetricos.EMABARAZOS,tbl_ant_obstetricos.PLANIFICACION,tbl_ant_obstetricos.FECHA_ULTIMA_MESTRU,
tbl_ant_patologicos.ANT_PATOLOGICO,tbl_ant_patologicos.TIPO_ANTECEDENTE,tbl_ant_patologicos.ENFERMEDAD,tbl_ant_patologicos.ALERGIAS,
tbl_ant_patologicos.HABITOS,tbl_ant_patologicos.CONSUMO_MEDICAMENTO,tbl_ant_obstetricos.PERIODO_MESTRUAL,tbl_galeria.IMAGEN,tbl_galeria.OBSERVACIONES,
tbl_facturas.TOTAL,tbl_facturas.SUB_TOTAL,tbl_facturas.IMPUESTO,tbl_facturas.DESCRIPCION

FROM 
tbl_consultas INNER JOIN 
tbl_pacientes INNER JOIN 
tbl_signos_vitales INNER JOIN 
tbl_diagnosticos INNER JOIN
tbl_examenes INNER JOIN
tbl_tratamientos INNER JOIN
tbl_ant_obstetricos INNER JOIN
tbl_ant_patologicos INNER JOIN
tbl_galeria INNER JOIN
tbl_facturas 

WHERE 
tbl_consultas.COD_CONSULTA = COD_CONSULTA AND
tbl_pacientes.COD_PACIENTE= tbl_consultas.COD_PACIENTE AND
tbl_signos_vitales.COD_SIGNOS=tbl_consultas.COD_SIGNOS AND
tbl_diagnosticos.COD_DIAGNOSTICO= tbl_consultas.COD_DIAGNOSTICO AND
tbl_examenes.COD_EXAMEN=tbl_consultas.COD_EXAMEN AND
tbl_tratamientos.COD_TRATAMIENTO=tbl_consultas.COD_TRATAMIENTO AND tbl_ant_obstetricos.COD_ANT_OBSTETRICOS=tbl_consultas.COD_ANT_OBSTETRICOS AND
tbl_ant_patologicos.COD_ANT_PATOLOGICO=tbl_consultas.COD_ANT_PATOLOGICO AND
tbl_galeria.COD_IMAGEN= tbl_consultas.COD_IIMAGEN AND
tbl_facturas.COD_FACTURA = tbl_consultas.COD_FACTURA;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_PACIENTE` (IN `COD_PACIENTE` INT)  BEGIN
START TRANSACTION;
SELECT p.PRI_NOMBRE, p.SEG_NOMBRE, p.PRI_APELLIDO,p.SEG_APELLIDO,p.GENERO,p.FECHA_NACIMIENTO,
p.EDAD,p.TIPO_ID,p.NUMERO_ID,p.ACTIVO_INACTIVO,p.CORREO,p.TELEFONO,p.DIRECCION,d.DEPARTAMENTO,
p.FECHA_REGISTRO,e.NOM_ENCARGADO, e.PARENTESCO, e.IDENTIFICACION, e.TELEFONO as TEL_ENCARGADO
FROM tbl_encargado e, tbl_pacientes p, tbl_departamentos d
where e.COD_ENCARGADO = p.COD_ENCARGADO
and d.COD_DEPARTAMENTO = p.COD_DEPARTAMENTO
and p.COD_PACIENTE = COD_PACIENTE;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_PACIENTES` ()  BEGIN
START TRANSACTION;
SELECT `COD_PACIENTE`, `PRI_NOMBRE`, `SEG_NOMBRE`, `PRI_APELLIDO`, `SEG_APELLIDO`, `GENERO`, `FECHA_NACIMIENTO`, `EDAD`, `TIPO_ID`, `NUMERO_ID`, `ACTIVO_INACTIVO`, `CORREO`, `TELEFONO`, `DIRECCION`, `COD_DEPARTAMENTO`, `COD_ENCARGADO`, `FECHA_REGISTRO` FROM `tbl_pacientes`
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_PACIENTE_ENCARGADO_DEPARTAMENTO` ()  BEGIN
START TRANSACTION;
SELECT p.COD_PACIENTE,p.PRI_NOMBRE, p.SEG_NOMBRE, p.PRI_APELLIDO,p.SEG_APELLIDO,p.GENERO,p.FECHA_NACIMIENTO,
p.EDAD,p.TIPO_ID,p.NUMERO_ID,p.ACTIVO_INACTIVO,p.CORREO,p.TELEFONO,p.DIRECCION,d.DEPARTAMENTO,
p.FECHA_REGISTRO,e.NOM_ENCARGADO, e.PARENTESCO, e.IDENTIFICACION, e.TELEFONO as TEL_ENCARGADO
FROM tbl_encargado e, tbl_pacientes p, tbl_departamentos d
where e.COD_ENCARGADO = p.COD_ENCARGADO
and d.COD_DEPARTAMENTO = p.COD_DEPARTAMENTO;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_PACIENTE_ENCARGADO_DEPARTAMENTO2` (IN `COD_PACIENTE` INT)  BEGIN
START TRANSACTION;
SELECT p.COD_PACIENTE,p.PRI_NOMBRE, p.SEG_NOMBRE, p.PRI_APELLIDO,p.SEG_APELLIDO,p.GENERO,p.FECHA_NACIMIENTO,
p.EDAD,p.TIPO_ID,p.NUMERO_ID,p.ACTIVO_INACTIVO,p.CORREO,p.TELEFONO,p.DIRECCION,d.DEPARTAMENTO,
p.FECHA_REGISTRO,e.NOM_ENCARGADO, e.PARENTESCO, e.IDENTIFICACION, e.TELEFONO as TEL_ENCARGADO
FROM tbl_encargado e, tbl_pacientes p, tbl_departamentos d
where e.COD_ENCARGADO = p.COD_ENCARGADO
and d.COD_DEPARTAMENTO = p.COD_DEPARTAMENTO
AND P.COD_PACIENTE = COD_PACIENTE;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_PACIENTE_TRATAMIENTOS_ENFERMEDADES` (IN `COD_PACIENTE` INT)  BEGIN
START TRANSACTION;

SELECT 
tbl_pacientes.PRI_NOMBRE,
tbl_pacientes.SEG_NOMBRE,
tbl_pacientes.EDAD,
tbl_pacientes.GENERO,
tbl_consultas.TIPO_CONSULTA,
tbl_tratamientos.MEDICAMENTO,
tbl_tratamientos.MARCA,
tbl_ant_patologicos.ANT_PATOLOGICO,
tbl_ant_patologicos.TIPO_ANTECEDENTE,
tbl_ant_patologicos.ENFERMEDAD,
tbl_ant_patologicos.ALERGIAS,
tbl_ant_patologicos.HABITOS,
tbl_ant_patologicos.CONSUMO_MEDICAMENTO,
tbl_galeria.IMAGEN,
tbl_galeria.OBSERVACIONES


FROM 
tbl_consultas INNER JOIN 
tbl_pacientes INNER JOIN 
tbl_diagnosticos INNER JOIN
tbl_tratamientos INNER JOIN
tbl_ant_patologicos INNER JOIN
tbl_galeria 

WHERE 
tbl_pacientes.COD_PACIENTE = COD_PACIENTE AND
tbl_pacientes.COD_PACIENTE= tbl_consultas.COD_PACIENTE AND
tbl_diagnosticos.COD_DIAGNOSTICO= tbl_consultas.COD_DIAGNOSTICO AND
tbl_tratamientos.COD_TRATAMIENTO=tbl_consultas.COD_TRATAMIENTO AND 
tbl_ant_patologicos.COD_ANT_PATOLOGICO=tbl_consultas.COD_ANT_PATOLOGICO AND
tbl_galeria.COD_IMAGEN= tbl_consultas.COD_IIMAGEN ;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_USUARIO` (IN `NOM_USUARIO` VARCHAR(20))  SELECT `NOM_USUARIO`, `TIPO_USUARIO`, `CONTRASEÑA`, `CORREO`, `FECHA_REGISTRO` FROM `tbl_usuarios` WHERE tbl_usuarios.NOM_USUARIO=NOM_USUARIO$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_USUARIOS` ()  BEGIN
START TRANSACTION;
SELECT `NOM_USUARIO`, `TIPO_USUARIO`, `CONTRASEÑA`, `CORREO`, `FECHA_REGISTRO` FROM `tbl_usuarios`;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_ANTECEDENTES_OBSTETRICOS` (IN `COD_ANT_OBSTETRICOS` INT, IN `MENARQUIA` VARCHAR(30), IN `EMABARAZOS` VARCHAR(30), IN `PLANIFICACION` VARCHAR(30), IN `PERIODO_MESTRUAL` VARCHAR(30), IN `FECHA_ULTIMA_MESTRU` VARCHAR(30))  BEGIN
START TRANSACTION;
UPDATE `tbl_ant_obstetricos` SET `MENARQUIA`=MENARQUIA,`EMABARAZOS`=EMABARAZOS,`PLANIFICACION`=PLANIFICACION,`PERIODO_MESTRUAL`=PERIODO_MESTRUAL,`FECHA_ULTIMA_MESTRU`=FECHA_ULTIMA_MESTRU WHERE tbl_ant_obstetricos.COD_ANT_OBSTETRICOS =COD_ANT_OBSTETRICOS;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_ANTECEDENTES_PATOLOGICOS` (IN `COD_ANT_PATOLOGICO` INT, IN `ANT_PATOLOGICO` VARCHAR(30), IN `TIPO_ANTECEDENTE` VARCHAR(30), IN `ENFERMEDAD` VARCHAR(30), IN `ALERGIAS` VARCHAR(30), IN `HABITOS` VARCHAR(30), IN `CONSUMO_MEDICAMENTO` VARCHAR(30))  BEGIN
START TRANSACTION;
UPDATE `tbl_ant_patologicos` SET`ANT_PATOLOGICO`=ANT_PATOLOGICO,`TIPO_ANTECEDENTE`=TIPO_ANTECEDENTE,`ENFERMEDAD`=ENFERMEDAD,
`ALERGIAS`=ALERGIAS,`HABITOS`=HABITOS,`CONSUMO_MEDICAMENTO`=CONSUMO_MEDICAMENTO WHERE tbl_ant_patologicos.COD_ANT_PATOLOGICO= COD_ANT_PATOLOGICO;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_CITA` (IN `COD_CITA` INT(11), IN `NUMERO_ID` VARCHAR(30), IN `ASUNTO_NOMBRE` VARCHAR(20), IN `LUGAR_CLINICA` VARCHAR(30), IN `FECHA_INICIO` DATETIME, IN `FECHA_FIN` DATETIME, IN `ESTADO_CITA` VARCHAR(2))  BEGIN
START TRANSACTION;
SELECT @COD_PACIENTE := COD_PACIENTE 
FROM tbl_pacientes WHERE tbl_pacientes.NUMERO_ID=NUMERO_ID;

UPDATE TBL_CITAS 
      SET COD_PACIENTE= @COD_PACIENTE,
          ASUNTO_NOMBRE = ASUNTO_NOMBRE,
          LUGAR_CLINICA = LUGAR_CLINICA,
          FECHA_INICIO = FECHA_INICIO,
          FECHA_FIN = FECHA_FIN,
          ESTADO_CITA = ESTADO_CITA, 
          FECHA_REGISTRO = CURRENT_TIMESTAMP()
      WHERE TBL_CITAS.COD_CITA =COD_CITA;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_CONSULTA` (IN `COD_CONSULTA` INT, INOUT `TIPO_CONSULTA` VARCHAR(30), INOUT `LUGAR` VARCHAR(30), INOUT `SEGURO_MEDICO` VARCHAR(30), INOUT `ASEGURADORA` VARCHAR(30), INOUT `RELACION_POLIZA` VARCHAR(30), INOUT `ESTATURA` VARCHAR(30), INOUT `SATO2` VARCHAR(30), INOUT `PESO` VARCHAR(30), INOUT `TEMPERATURA` VARCHAR(30), INOUT `PRESIÓN_ALTERIAL` VARCHAR(30), INOUT `FRECUENCIA_CARDIACA` VARCHAR(30), INOUT `FRECUENCIA_RESPIRATORIA` VARCHAR(30), INOUT `NOTAS` VARCHAR(30), INOUT `DESCRIPCION_SIGNOS` VARCHAR(30), INOUT `CIE` VARCHAR(30), INOUT `NOMBRE_DIAGNOSTICO` VARCHAR(30), INOUT `EQUIVALENCIAS` VARCHAR(30), INOUT `DESCRIPCION_CIE` VARCHAR(30), INOUT `MEDICAMENTO` VARCHAR(30), INOUT `MARCA` VARCHAR(30), INOUT `CANTIDAD` INT(30), INOUT `DOSIS_MEDICAMENTO` VARCHAR(30), INOUT `DESCRIPCION_TRATAMIENTO` VARCHAR(30), INOUT `NOMBRE_EXAMEN` VARCHAR(30), INOUT `ETIQUETAS` VARCHAR(30), INOUT `CODIGO` VARCHAR(30), INOUT `MENARQUIA` VARCHAR(30), INOUT `EMABARAZOS` VARCHAR(30), INOUT `PLANIFICACION` VARCHAR(30), INOUT `PERIODO_MESTRUAL` VARCHAR(30), INOUT `FECHA_ULTIMA_MESTRU` DATETIME, INOUT `ANT_PATOLOGICO` VARCHAR(30), INOUT `TIPO_ANTECEDENTE` VARCHAR(30), INOUT `ENFERMEDAD` VARCHAR(30), INOUT `ALERGIAS` VARCHAR(30), INOUT `HABITOS` VARCHAR(30), INOUT `CONSUMO_MEDICAMENTO` VARCHAR(30), INOUT `IMAGEN` VARCHAR(30), INOUT `OBSERVACIONES_IMAGEN` VARCHAR(30), INOUT `SUB_TOTAL` DECIMAL, INOUT `IMPUESTO` DECIMAL, INOUT `TOTAL` DECIMAL, INOUT `DESCRIPCION_PAGO` VARCHAR(30))  BEGIN
START TRANSACTION;
UPDATE `tbl_consultas` c 
JOIN tbl_pacientes p on c.COD_PACIENTE = p.COD_PACIENTE
JOIN tbl_signos_vitales s on c.COD_SIGNOS = s.COD_SIGNOS
JOIN tbl_diagnosticos d on c.COD_DIAGNOSTICO =d.COD_DIAGNOSTICO
JOIN tbl_examenes e on c.COD_EXAMEN = e.COD_EXAMEN  
JOIN tbl_tratamientos t on c.COD_TRATAMIENTO = t.COD_TRATAMIENTO
JOIN tbl_ant_obstetricos a on c.COD_ANT_OBSTETRICOS = a.COD_ANT_OBSTETRICOS
JOIN tbl_ant_patologicos ap on c.COD_ANT_PATOLOGICO= ap.COD_ANT_PATOLOGICO
JOIN tbl_galeria g on c.COD_IIMAGEN = g.COD_IMAGEN
JOIN tbl_facturas f on c.COD_FACTURA = f.COD_FACTURA 
SET 

C.COD_PACIENTE= c.COD_PACIENTE,
C.TIPO_CONSULTA=TIPO_CONSULTA,
C.LUGAR=LUGAR,
C.SEGURO_MEDICO=SEGURO_MEDICO,
C.ASEGURADORA= ASEGURADORA,
C.RELACION_POLIZA=RELACION_POLIZA,
C.COD_SIGNOS= C.COD_SIGNOS,
C.COD_DIAGNOSTICO = C.COD_DIAGNOSTICO,
C.COD_EXAMEN= C.COD_EXAMEN,
C.COD_TRATAMIENTO= C.COD_TRATAMIENTO,
C.COD_ANT_OBSTETRICOS= C.COD_ANT_OBSTETRICOS,
C.COD_ANT_PATOLOGICO= C.COD_ANT_PATOLOGICO,
C.COD_IIMAGEN= C.COD_IIMAGEN,
C.COD_FACTURA= C.COD_FACTURA,
C.FECHA_REGISTRO = CURRENT_TIMESTAMP(),
S.ESTATURA=ESTATURA,
S.SATO2= SATO2,
S.PESO= PESO,
S.TEMPERATURA= TEMPERATURA,
S.PRESIÓN_ALTERIAL= PRESIÓN_ALTERIAL,
S.FRECUENCIA_CARDIACA =FRECUENCIA_CARDIACA,
S.FRECUENCIA_RESPIRATORIA= FRECUENCIA_RESPIRATORIA,
S.NOTAS= NOTAS,
S.DESCRIPCION= DESCRIPCION_SIGNOS,
S.FECHA_REGISTRO= CURRENT_TIMESTAMP(),
D.CIE= CIE,
D.NOMBRE_DIAGNOSTICO= NOMBRE_DIAGNOSTICO,
D.EQUIVALENCIAS= EQUIVALENCIAS,
D.DESCRIPCION= DESCRIPCION_CIE,
E.NOMBRE_EXAMEN= NOMBRE_EXAMEN,
E.ETIQUETAS= ETIQUETAS,
E.CODIGO = CODIGO,
T.MEDICAMENTO= MEDICAMENTO,
T.MARCA= MARCA,
T.CANTIDAD= CANTIDAD,
T.DESCRIPCION = DESCRIPCION_TRATAMIENTO,
T.DOSIS_INDICACIONES= DOSIS_MEDICAMENTO,
T.DESCRIPCION= DESCRIPCION_TRATAMIENTO,
A.MENARQUIA=MENARQUIA,
A.EMABARAZOS=EMABARAZOS,
A.PLANIFICACION= PLANIFICACION,
A.PERIODO_MESTRUAL= PERIODO_MESTRUAL,
A.FECHA_ULTIMA_MESTRU= FECHA_ULTIMA_MESTRU,
AP.ANT_PATOLOGICO= ANT_PATOLOGICO,
AP.TIPO_ANTECEDENTE= TIPO_ANTECEDENTE,
AP.ENFERMEDAD= ENFERMEDAD,
AP.ALERGIAS= ALERGIAS,
AP.HABITOS= HABITOS,
AP.CONSUMO_MEDICAMENTO= CONSUMO_MEDICAMENTO,
G.IMAGEN= IMAGEN,
G.OBSERVACIONES = OBSERVACIONES_IMAGEN,
F.SUB_TOTAL= SUB_TOTAL,
F.IMPUESTO = IMPUESTO,
F.TOTAL = TOTAL,
F.DESCRIPCION= DESCRIPCION_PAGO
WHERE c.COD_CONSULTA=COD_CONSULTA ;


COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_COSULTA_PACIENTE` (IN `COD_PACIENTE` INT, IN `TIPO_CONSULTA` VARCHAR(30), IN `LUGAR` VARCHAR(30), IN `SEGURO_MEDICO` VARCHAR(30), IN `ASEGURADORA` VARCHAR(30), IN `RELACION_POLIZA` VARCHAR(30), IN `ESTATURA` VARCHAR(30), IN `SATO2` VARCHAR(30), IN `PESO` VARCHAR(30), IN `TEMPERATURA` VARCHAR(30), IN `PRESIÓN_ALTERIAL` VARCHAR(30), IN `FRECUENCIA_CARDIACA` VARCHAR(30), IN `FRECUENCIA_RESPIRATORIA` VARCHAR(30), IN `NOTAS` VARCHAR(30), IN `DESCRIPCION_SIGNOS` VARCHAR(30), IN `CIE` VARCHAR(30), IN `NOMBRE_DIAGNOSTICO` VARCHAR(30), IN `EQUIVALENCIAS` VARCHAR(30), IN `DESCRIPCION_CIE` VARCHAR(30), IN `MEDICAMENTO` VARCHAR(30), IN `MARCA` VARCHAR(30), IN `CANTIDAD` INT(30), IN `DOSIS_MEDICAMENTO` VARCHAR(30), IN `DESCRIPCION_TRATAMIENTO` VARCHAR(30), IN `NOMBRE_EXAMEN` VARCHAR(30), IN `ETIQUETAS` VARCHAR(30), IN `CODIGO` VARCHAR(30), IN `MENARQUIA` VARCHAR(30), IN `EMABARAZOS` VARCHAR(30), IN `PLANIFICACION` VARCHAR(30), IN `PERIODO_MESTRUAL` VARCHAR(30), IN `FECHA_ULTIMA_MESTRU` DATETIME, IN `ANT_PATOLOGICO` VARCHAR(30), IN `TIPO_ANTECEDENTE` VARCHAR(30), IN `ENFERMEDAD` VARCHAR(30), IN `ALERGIAS` VARCHAR(30), IN `HABITOS` VARCHAR(30), IN `CONSUMO_MEDICAMENTO` VARCHAR(30), IN `IMAGEN` VARCHAR(30), IN `OBSERVACIONES_IMAGEN` VARCHAR(30), IN `SUB_TOTAL` DECIMAL, IN `IMPUESTO` DECIMAL, IN `TOTAL` DECIMAL, IN `DESCRIPCION_PAGO` VARCHAR(30))  BEGIN
START TRANSACTION;


SELECT @COD_PACIENTE := tbl_pacientes.COD_PACIENTE,
@COD_CONSULTA := tbl_consultas.COD_CONSULTA,
@COD_SIGNOS := tbl_signos_vitales.COD_SIGNOS,
@COD_DIAGNOSTICO := tbl_diagnosticos.COD_DIAGNOSTICO,
@COD_EXAMEN := tbl_examenes.COD_EXAMEN,
@COD_TRATAMIENTO := tbl_tratamientos.COD_TRATAMIENTO,
@COD_ANT_OBSTETRICOS := tbl_ant_obstetricos.COD_ANT_OBSTETRICOS,
@COD_ANT_PATOLOGICO := tbl_ant_patologicos.COD_ANT_PATOLOGICO,
@COD_IMAGEN := tbl_galeria.COD_IMAGEN,
@COD_FACTURA := tbl_facturas.COD_FACTURA
FROM 
tbl_consultas INNER JOIN 
tbl_pacientes INNER JOIN 
tbl_signos_vitales INNER JOIN 
tbl_diagnosticos INNER JOIN
tbl_examenes INNER JOIN
tbl_tratamientos INNER JOIN
tbl_ant_obstetricos INNER JOIN
tbl_ant_patologicos INNER JOIN
tbl_galeria INNER JOIN
tbl_facturas 
WHERE 
tbl_pacientes.COD_PACIENTE =COD_PACIENTE AND
tbl_pacientes.COD_PACIENTE= tbl_consultas.COD_PACIENTE AND
tbl_signos_vitales.COD_SIGNOS=tbl_consultas.COD_SIGNOS AND
tbl_diagnosticos.COD_DIAGNOSTICO= tbl_consultas.COD_DIAGNOSTICO AND
tbl_examenes.COD_EXAMEN=tbl_consultas.COD_EXAMEN AND
tbl_tratamientos.COD_TRATAMIENTO=tbl_consultas.COD_TRATAMIENTO AND tbl_ant_obstetricos.COD_ANT_OBSTETRICOS=tbl_consultas.COD_ANT_OBSTETRICOS AND tbl_ant_patologicos.COD_ANT_PATOLOGICO=tbl_consultas.COD_ANT_PATOLOGICO AND tbl_galeria.COD_IMAGEN= tbl_consultas.COD_IIMAGEN AND tbl_facturas.COD_FACTURA = tbl_consultas.COD_FACTURA;



UPDATE `tbl_consultas` 
SET `COD_CONSULTA`=@COD_CONSULTA,
`COD_PACIENTE`=@COD_PACIENTE,
`TIPO_CONSULTA`=TIPO_CONSULTA,
`LUGAR`=LUGAR,
`SEGURO_MEDICO`=SEGURO_MEDICO,
`ASEGURADORA`=ASEGURADORA,
`RELACION_POLIZA`=RELACION_POLIZA,
`COD_SIGNOS`=@COD_SIGNOS,
`COD_DIAGNOSTICO`=@COD_DIAGNOSTICO,
`COD_EXAMEN`=@COD_EXAMEN,
`COD_TRATAMIENTO`=@COD_TRATAMIENTO,
`COD_ANT_OBSTETRICOS`=@COD_ANT_OBSTETRICOS,
`COD_ANT_PATOLOGICO`=@COD_ANT_PATOLOGICO,
`COD_IIMAGEN`=@COD_IIMAGEN,
`COD_FACTURA`=@COD_FACTURA,
`FECHA_REGISTRO`= CURRENT_TIMESTAMP() WHERE tbl_consultas.COD_CONSULTA=@COD_CONSULTA;

UPDATE `tbl_signos_vitales`
SET `ESTATURA`= ESTATURA,
`SATO2`= SATO2,`PESO`= PESO,
`TEMPERATURA`= TEMPERATURA,
`PRESIÓN_ALTERIAL`= PRESIÓN_ALTERIAL,
`FRECUENCIA_CARDIACA`= FRECUENCIA_CARDIACA,
`FRECUENCIA_RESPIRATORIA`= FRECUENCIA_RESPIRATORIA,
`NOTAS`= NOTAS,
`DESCRIPCION`= DESCRIPCION_SIGNOS,
`FECHA_REGISTRO`= CURRENT_TIMESTAMP 
WHERE tbl_signos_vitales.COD_SIGNOS = @COD_SIGNOS;

UPDATE `tbl_diagnosticos` 
SET`CIE`=CIE,
`NOMBRE_DIAGNOSTICO`=NOMBRE_DIAGNOSTICO,
`EQUIVALENCIAS`=EQUIVALENCIAS,
`DESCRIPCION`=DESCRIPCION_CIE WHERE tbl_diagnosticos.COD_DIAGNOSTICO = @COD_DIAGNOSTICO;

UPDATE `tbl_tratamientos` SET 
`MEDICAMENTO`=MEDICAMENTO,
`MARCA`= MARCA,
`CANTIDAD`=CANTIDAD,
`DOSIS_INDICACIONES`=DOSIS_MEDICAMENTO,
`DESCRIPCION`=DESCRIPCION_TRATAMIENTO WHERE tbl_tratamientos.COD_TRATAMIENTO = @COD_TRATAMIENTO;

UPDATE `tbl_examenes` 
SET `NOMBRE_EXAMEN`=NOMBRE_EXAMEN,
`ETIQUETAS`=ETIQUETAS,
`CODIGO`=CODIGO WHERE 
tbl_examenes.COD_EXAMEN= @COD_EXAMEN;

UPDATE `tbl_ant_obstetricos` 
SET`MENARQUIA`=MENARQUIA,
`EMABARAZOS`=EMABARAZOS,
`PLANIFICACION`=PLANIFICACION,
`PERIODO_MESTRUAL`=PERIODO_MESTRUAL,
`FECHA_ULTIMA_MESTRU`=FECHA_ULTIMA_MESTRU WHERE tbl_ant_obstetricos.COD_ANT_OBSTETRICOS = @COD_ANT_OBSTETRICOS;

UPDATE `tbl_ant_patologicos` 
SET`ANT_PATOLOGICO`=ANT_PATOLOGICO,
`TIPO_ANTECEDENTE`=TIPO_ANTECEDENTE,
`ENFERMEDAD`=ENFERMEDAD,
`ALERGIAS`=ALERGIAS,
`HABITOS`=HABITOS,
`CONSUMO_MEDICAMENTO`=CONSUMO_MEDICAMENTO WHERE tbl_ant_patologicos.COD_ANT_PATOLOGICO = @COD_ANT_PATOLOGICO;

UPDATE `tbl_galeria` 
SET `IMAGEN`=IMAGEN,
`OBSERVACIONES`=OBSERVACIONES_IMAGEN 
WHERE tbl_galeria.COD_IMAGEN = @COD_IMAGEN;

UPDATE `tbl_facturas` SET `SUB_TOTAL`=SUB_TOTAL,`IMPUESTO`=IMPUESTO,`TOTAL`=TOTAL,
`DESCRIPCION`=DESCRIPCION_PAGO WHERE  tbl_facturas.COD_FACTURA= @COD_FACTURA;


COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_DIAGNOSTICO` (IN `COD_DIAGNOSTICO` INT, IN `CIE` VARCHAR(30), IN `NOMBRE_DIAGNOSTICO` VARCHAR(30), IN `EQUIVALENCIAS` VARCHAR(30), IN `DESCRIPCION` VARCHAR(30))  BEGIN
START TRANSACTION;
UPDATE `tbl_diagnosticos` SET `CIE`=CIE,`NOMBRE_DIAGNOSTICO`=NOMBRE_DIAGNOSTICO,`EQUIVALENCIAS`=EQUIVALENCIAS,`DESCRIPCION`=DESCRIPCION WHERE tbl_diagnosticos.COD_DIAGNOSTICO=COD_DIAGNOSTICO;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_EXAMEN` (IN `COD_EXAMEN` INT, IN `NOMBRE_EXAMENNOMBRE_EXAMEN` VARCHAR(30), IN `ETIQUETAS` VARCHAR(30), IN `CODIGO` VARCHAR(30))  BEGIN 
START TRANSACTION;
UPDATE `tbl_examenes` SET `NOMBRE_EXAMEN`=NOMBRE_EXAMEN,`ETIQUETAS`=ETIQUETAS,`CODIGO`=CODIGO WHERE tbl_examenes.COD_EXAMEN= COD_EXAMEN;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_FACTURA` (IN `COD_FACTURA` INT, IN `SUB_TOTAL` DECIMAL, IN `IMPUESTO` DECIMAL, IN `TOTAL` DECIMAL, IN `DESCRIPCION` VARCHAR(30))  BEGIN
START TRANSACTION;
UPDATE `tbl_facturas` SET `SUB_TOTAL`=SUB_TOTAL,`IMPUESTO`=IMPUESTO,`TOTAL`='[value-4]',`DESCRIPCION`='[value-5]' WHERE  tbl_facturas.COD_FACTURA= COD_FACTURA;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_FACTURA_PRUEBA` (IN `COD_PACIENTE` INT, IN `TIPO_CONSULTA` VARCHAR(30), IN `LUGAR` VARCHAR(30), IN `SEGURO_MEDICO` VARCHAR(30), IN `ASEGURADORA` VARCHAR(30), IN `RELACION_POLIZA` VARCHAR(30), IN `SUB_TOTAL` INT, IN `IMPUESTO` INT, IN `TOTAL` INT, IN `DESCRIPCION_PAGO` VARCHAR(30))  BEGIN
START TRANSACTION;
SELECT @COD_PACIENTE := tbl_pacientes.COD_PACIENTE,
@COD_CONSULTA := tbl_consultas.COD_CONSULTA,
@COD_SIGNOS := tbl_signos_vitales.COD_SIGNOS,
@COD_DIAGNOSTICO := tbl_diagnosticos.COD_DIAGNOSTICO,
@COD_EXAMEN := tbl_examenes.COD_EXAMEN,
@COD_TRATAMIENTO := tbl_tratamientos.COD_TRATAMIENTO,
@COD_ANT_OBSTETRICOS := tbl_ant_obstetricos.COD_ANT_OBSTETRICOS,
@COD_ANT_PATOLOGICO := tbl_ant_patologicos.COD_ANT_PATOLOGICO,
@COD_IMAGEN := tbl_galeria.COD_IMAGEN,
@COD_FACTURA := tbl_facturas.COD_FACTURA
FROM 
tbl_consultas INNER JOIN 
tbl_pacientes INNER JOIN 
tbl_signos_vitales INNER JOIN 
tbl_diagnosticos INNER JOIN
tbl_examenes INNER JOIN
tbl_tratamientos INNER JOIN
tbl_ant_obstetricos INNER JOIN
tbl_ant_patologicos INNER JOIN
tbl_galeria INNER JOIN
tbl_facturas 
WHERE 
tbl_pacientes.COD_PACIENTE =COD_PACIENTE AND
tbl_pacientes.COD_PACIENTE= tbl_consultas.COD_PACIENTE AND
tbl_signos_vitales.COD_SIGNOS=tbl_consultas.COD_SIGNOS AND
tbl_diagnosticos.COD_DIAGNOSTICO= tbl_consultas.COD_DIAGNOSTICO AND
tbl_examenes.COD_EXAMEN=tbl_consultas.COD_EXAMEN AND
tbl_tratamientos.COD_TRATAMIENTO=tbl_consultas.COD_TRATAMIENTO AND tbl_ant_obstetricos.COD_ANT_OBSTETRICOS=tbl_consultas.COD_ANT_OBSTETRICOS AND tbl_ant_patologicos.COD_ANT_PATOLOGICO=tbl_consultas.COD_ANT_PATOLOGICO AND tbl_galeria.COD_IMAGEN= tbl_consultas.COD_IIMAGEN AND tbl_facturas.COD_FACTURA = tbl_consultas.COD_FACTURA;

UPDATE `tbl_consultas` 
SET `COD_CONSULTA`=@COD_CONSULTA,
`COD_PACIENTE`=@COD_PACIENTE,
`TIPO_CONSULTA`=TIPO_CONSULTA,
`LUGAR`=LUGAR,
`SEGURO_MEDICO`=SEGURO_MEDICO,
`ASEGURADORA`=ASEGURADORA,
`RELACION_POLIZA`=RELACION_POLIZA,
`COD_SIGNOS`=@COD_SIGNOS,
`COD_DIAGNOSTICO`=@COD_DIAGNOSTICO,
`COD_EXAMEN`=@COD_EXAMEN,
`COD_TRATAMIENTO`=@COD_TRATAMIENTO,
`COD_ANT_OBSTETRICOS`=@COD_ANT_OBSTETRICOS,
`COD_ANT_PATOLOGICO`=@COD_ANT_PATOLOGICO,
`COD_IIMAGEN`=@COD_IIMAGEN,
`COD_FACTURA`=@COD_FACTURA,
`FECHA_REGISTRO`= CURRENT_TIMESTAMP() WHERE tbl_consultas.COD_CONSULTA=@COD_CONSULTA;

UPDATE `tbl_facturas` SET `SUB_TOTAL`=SUB_TOTAL,`IMPUESTO`=IMPUESTO,`TOTAL`=TOTAL,
`DESCRIPCION`=DESCRIPCION_PAGO WHERE  tbl_facturas.COD_FACTURA= @COD_FACTURA;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_IMAGEN` (IN `COD_IMAGEN` INT, IN `IMAGEN` VARCHAR(30), IN `OBSERVACIONES` VARCHAR(30))  BEGIN
START TRANSACTION;
UPDATE `tbl_galeria` SET `IMAGEN`=IMAGEN,`OBSERVACIONES`=OBSERVACIONES WHERE tbl_galeria.COD_IMAGEN= COD_IMAGEN;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_PACIENTE_ENCARGADO` (IN `COD_PACIENTE` INT(11), IN `PRI_NOMBRE` VARCHAR(30), IN `SEG_NOMBRE` VARCHAR(30), IN `PRI_APELLIDO` VARCHAR(30), IN `SEG_APELLIDO` VARCHAR(30), IN `GENERO` VARCHAR(30), IN `FECHA_NACIMIENTO` DATE, IN `EDAD` TINYINT(4), IN `TIPO_ID` VARCHAR(30), IN `NUMERO_ID` VARCHAR(30), IN `ACTIVO_INACTIVO` VARCHAR(30), IN `CORREO` VARCHAR(40), IN `TELEFONO_PAC` VARCHAR(30), IN `DIRECCION` VARCHAR(100), IN `DEPARTAMENTO` VARCHAR(30), IN `NOM_ENCARGADO` VARCHAR(30), IN `PARENTESCO` VARCHAR(30), IN `IDENTIFICACION` VARCHAR(30), IN `TELEFONO` VARCHAR(30))  BEGIN
START TRANSACTION;

SELECT @COD_ENCARGADO := COD_ENCARGADO FROM tbl_pacientes p where p.COD_PACIENTE = COD_PACIENTE;
SELECT @COD_DEPARTAMENTO := COD_DEPARTAMENTO FROM tbl_departamentos d WHERE d.DEPARTAMENTO =DEPARTAMENTO;

UPDATE tbl_pacientes p set p.PRI_NOMBRE = PRI_NOMBRE,p.SEG_NOMBRE = SEG_NOMBRE, p.PRI_APELLIDO = PRI_APELLIDO, p.SEG_APELLIDO = SEG_APELLIDO,
 p.GENERO = GENERO, p.FECHA_NACIMIENTO = FECHA_NACIMIENTO, p.EDAD = EDAD, p.TIPO_ID = TIPO_ID, p.NUMERO_ID = NUMERO_ID, p.ACTIVO_INACTIVO = ACTIVO_INACTIVO, 
 p.CORREO = CORREO, p.TELEFONO = TELEFONO_PAC, p.DIRECCION = DIRECCION, p.COD_DEPARTAMENTO = @COD_DEPARTAMENTO, p.FECHA_REGISTRO = NOW()
 WHERE p.COD_PACIENTE = COD_PACIENTE;
 
 UPDATE tbl_encargado e set e.NOM_ENCARGADO = NOM_ENCARGADO, e.PARENTESCO = PARENTESCO, 
 e.IDENTIFICACION = IDENTIFICACION, e.TELEFONO = TELEFONO
 WHERE e.COD_ENCARGADO = @COD_ENCARGADO;
 
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_PACIENTE_ENCARGADO_DEPARTAMENTO` (IN `COD_PACIENTE` INT(11), IN `PRI_NOMBRE` VARCHAR(30), IN `SEG_NOMBRE` VARCHAR(30), IN `PRI_APELLIDO` VARCHAR(30), IN `SEG_APELLIDO` VARCHAR(30), IN `GENERO` VARCHAR(1), IN `FECHA_NACIMIENTO` DATE, IN `EDAD` TINYINT(4), IN `TIPO_ID` VARCHAR(30), IN `NUMERO_ID` VARCHAR(30), IN `ACTIVO_INACTIVO` VARCHAR(2), IN `CORREO` VARCHAR(40), IN `TELEFONO_PAC` VARCHAR(30), IN `DIRECCION` VARCHAR(100), IN `COD_DEPARTAMENTO` INT(11), IN `FECHA_REGISTRO` DATETIME, IN `COD_ENCARGADO` INT(11), IN `NOM_ENCARGADO` VARCHAR(30), IN `PARENTESCO` VARCHAR(30), IN `IDENTIFICACION` VARCHAR(30), IN `TELEFONO` VARCHAR(30))  BEGIN
START TRANSACTION;

UPDATE tbl_pacientes p, tbl_encargado e set p.PRI_NOMBRE = PRI_NOMBRE,p.SEG_NOMBRE = SEG_NOMBRE, p.PRI_APELLIDO = PRI_APELLIDO, p.SEG_APELLIDO = SEG_APELLIDO,
 p.GENERO = GENERO, p.FECHA_NACIMIENTO = FECHA_NACIMIENTO, p.EDAD = EDAD,
 p.TIPO_ID = TIPO_ID, p.NUMERO_ID = NUMERO_ID, p.ACTIVO_INACTIVO = ACTIVO_INACTIVO, p.CORREO = CORREO, p.TELEFONO = TELEFONO_PAC, 
 p.DIRECCION = DIRECCION, P.COD_DEPARTAMENTO = COD_DEPARTAMENTO, p.FECHA_REGISTRO = FECHA_REGISTRO,
 e.NOM_ENCARGADO = NOM_ENCARGADO,e.PARENTESCO = PARENTESCO, e.IDENTIFICACION = IDENTIFICACION, e.TELEFONO = TELEFONO
 WHERE  p.COD_ENCARGADO = e.COD_ENCARGADO
 AND p.COD_PACIENTE = COD_PACIENTE;


COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_SIGNOS_VITALES` (IN `COD_SIGNOS` INT, INOUT `ESTATURA` VARCHAR(30), IN `SATO2` VARCHAR(30), IN `PESO` VARCHAR(30), IN `TEMPERATURA` VARCHAR(30), IN `PRESIÓN_ALTERIAL` VARCHAR(30), IN `FRECUENCIA_CARDIACA` VARCHAR(30), IN `FRECUENCIA_RESPIRATORIA` VARCHAR(30), IN `NOTAS` VARCHAR(30), IN `DESCRIPCION` VARCHAR(30), IN `FECHA_REGISTRO` DATETIME)  BEGIN
START TRANSACTION;
UPDATE `tbl_signos_vitales` SET `ESTATURA`= ESTATURA,`SATO2`= SATO2,`PESO`= PESO,`TEMPERATURA`= TEMPERATURA,`PRESIÓN_ALTERIAL`= PRESIÓN_ALTERIAL,
`FRECUENCIA_CARDIACA`= FRECUENCIA_CARDIACA,`FRECUENCIA_RESPIRATORIA`= FRECUENCIA_RESPIRATORIA
,`NOTAS`= NOTAS,`DESCRIPCION`= DESCRIPCION,`FECHA_REGISTRO`= FECHA_REGISTRO WHERE tbl_signos_vitales.COD_SIGNOS = COD_SIGNOS;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_TRATAMIENTO` (IN `COD_TRATAMIENTO` INT, INOUT `MEDICAMENTO` VARCHAR(30), INOUT `MARCA` VARCHAR(30), INOUT `CANTIDAD` TINYINT(4), INOUT `DOSIS_MEDICAMENTO` VARCHAR(30), INOUT `DESCRIPCION` VARCHAR(30))  BEGIN
START TRANSACTION;

UPDATE `tbl_tratamientos` SET 
`MEDICAMENTO`=MEDICAMENTO,
`MARCA`=MARCA,
`CANTIDAD`=CANTIDAD,
`DOSIS/INDICACIONES`=DOSIS_MEDICAMENTO,
`DESCRIPCION`=DESCRIPCION WHERE tbl_tratamientos.COD_TRATAMIENTO=COD_TRATAMIENTO;

COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_USUARIO` (IN `COD_USUARIO` INT(10), INOUT `NOM_USUARIO` VARCHAR(20), INOUT `TIPO_USUARIO` VARCHAR(20), INOUT `CONTRASEÑA` VARCHAR(20), INOUT `CORREO` VARCHAR(30), IN `FECHA_REGISTRO` DATETIME)  BEGIN
START TRANSACTION;
UPDATE `tbl_usuarios` SET `COD_USUARIO`= COD_USUARIO,`NOM_USUARIO`=NOM_USUARIO,`TIPO_USUARIO`=TIPO_USUARIO,`CONTRASEÑA`=CONTRASEÑA,`CORREO`=CORREO,`FECHA_REGISTRO`=FECHA_REGISTRO WHERE tbl_usuarios.COD_USUARIO =COD_USUARIO;
COMMIT;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP__INSERT_SEGUIMIENTO_SIGNOS_VITALES_PACIENTE` (IN `COD_PACIENTE` INT, IN `ESTATURA` VARCHAR(30), IN `SATO2` VARCHAR(30), IN `PESO` VARCHAR(30), IN `TEMPERATURA` VARCHAR(30), IN `PRESIÓN_ALTERIAL` VARCHAR(30), IN `FRECUENCIA_CARDIACA` VARCHAR(30), IN `NOTAS` VARCHAR(30), IN `DESCRIPCION_SIGNOS` VARCHAR(30), IN `FECHA_REGISTRO_SIGNOS` DATETIME)  BEGIN
START TRANSACTION;

INSERT INTO `tbl_signos_vitales`(`COD_SIGNOS`, `ESTATURA`, `SATO2`, `PESO`, `TEMPERATURA`, `PRESIÓN_ALTERIAL`, `FRECUENCIA_CARDIACA`, `FRECUENCIA_RESPIRATORIA`, `NOTAS`, `DESCRIPCION`, `FECHA_REGISTRO`) VALUES (COD_SIGNOS, ESTATURA,SATO2, PESO, TEMPERATURA, PRESIÓN_ALTERIAL,FRECUENCIA_CARDIACA,FRECUENCIA_RESPIRATORIA, NOTAS,DESCRIPCION_SIGNOS,FECHA_REGISTRO_SIGNOS);
/********/
SELECT @COD_SIGNOS := MAX(COD_SIGNOS) FROM tbl_signos_vitales ;

/*********/
SELECT @COD_DIAGNOSTICO := MAX(COD_DIAGNOSTICO)+1 FROM tbl_diagnosticos;
/*********************/
SELECT @COD_EXAMEN := MAX(COD_EXAMEN)+1 FROM tbl_examenes;
/**********/
SELECT @COD_TRATAMIENTO :=MAX(COD_TRATAMIENTO)+1  FROM tbl_tratamientos;
/*********/
/******/
SELECT @COD_ANT_OBSTETRICOS := MAX(COD_ANT_OBSTETRICOS)+1 FROM tbl_ant_obstetricos;
/*************/
/************/
SELECT @COD_ANT_PATOLOGICO := MAX(COD_ANT_PATOLOGICO)+1 FROM tbl_ant_patologicos;
/*************/
/******/
SELECT @COD_IMAGEN:= MAX(COD_IMAGEN)+1 FROM tbl_galeria;
/***************/

/****************/
SELECT @COD_FACTURA := MAX(COD_FACTURA)+1 FROM tbl_facturas;
/**********/
INSERT INTO `tbl_consultas`(`COD_CONSULTA`, `COD_PACIENTE`, `TIPO_CONSULTA`, `LUGAR`, `SEGURO_MEDICO`, `ASEGURADORA`, `RELACION_POLIZA`, `COD_SIGNOS`, `COD_DIAGNOSTICO`, `COD_EXAMEN`, `COD_TRATAMIENTO`, `COD_ANT_OBSTETRICOS`, `COD_ANT_PATOLOGICO`, `COD_IIMAGEN`, `COD_FACTURA`, `FECHA_REGISTRO`) VALUES (@COD_CONSULTA,COD_PACIENTE, '', '', '', '','', @COD_SIGNOS, '','','', '','', '', '', '0-0-0');
/**************************/


COMMIT;
END$$



DROP PROCEDURE IF EXISTS `SP_INSERT_PACIENTE_ENCARGADO_DEPARTAMENTO`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_PACIENTE_ENCARGADO_DEPARTAMENTO` (IN `PRI_NOMBRE` VARCHAR(30), IN `SEG_NOMBRE` VARCHAR(30), IN `PRI_APELLIDO` VARCHAR(30), IN `SEG_APELLIDO` VARCHAR(30), IN `GENERO` VARCHAR(30), IN `FECHA_NACIMIENTO` DATE, IN `EDAD` TINYINT(4), IN `TIPO_ID` VARCHAR(30), IN `NUMERO_ID` VARCHAR(30), IN `ACTIVO_INACTIVO` VARCHAR(30), IN `CORREO` VARCHAR(40), IN `TELEFONO_PAC` VARCHAR(30), IN `DIRECCION` VARCHAR(100), IN `DEPARTAMENTO` VARCHAR(30), IN `IDENTIFICACION` VARCHAR(30), IN `NOM_ENCARGADO` VARCHAR(30), IN `TELEFONO` VARCHAR(30), IN `PARENTESCO` VARCHAR(30))  BEGIN
START TRANSACTION;
INSERT INTO `tbl_encargado`( `NOM_ENCARGADO`, `PARENTESCO`, `IDENTIFICACION`, `TELEFONO`) VALUES (NOM_ENCARGADO,PARENTESCO,IDENTIFICACION,TELEFONO);
/********************/
SELECT @COD_ENCARGADO :=MAX(COD_ENCARGADO) FROM tbl_encargado;
SELECT @COD_DEPARTAMENTO := COD_DEPARTAMENTO FROM tbl_departamentos WHERE tbl_departamentos.DEPARTAMENTO =DEPARTAMENTO;
/********************/
INSERT INTO `tbl_pacientes`(`PRI_NOMBRE`, `SEG_NOMBRE`, `PRI_APELLIDO`, `SEG_APELLIDO`, `GENERO`, `FECHA_NACIMIENTO`, `EDAD`, `TIPO_ID`, `NUMERO_ID`, `ACTIVO_INACTIVO`, `CORREO`, `TELEFONO`, `DIRECCION`, `COD_DEPARTAMENTO`, `COD_ENCARGADO`, `FECHA_REGISTRO`) VALUES (PRI_NOMBRE,SEG_NOMBRE,PRI_APELLIDO,SEG_APELLIDO,GENERO,FECHA_NACIMIENTO,EDAD,TIPO_ID,NUMERO_ID,ACTIVO_INACTIVO
,CORREO,TELEFONO_PAC,DIRECCION,@COD_DEPARTAMENTO,@COD_ENCARGADO,current_timestamp());
COMMIT;
END$$


/*SELECT*/

DROP PROCEDURE IF EXISTS `SP_SELECT_PACIENTE_ENCARGADO_DEPARTAMENTO`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_PACIENTE_ENCARGADO_DEPARTAMENTO` ()  BEGIN
START TRANSACTION;
SELECT p.COD_PACIENTE,p.PRI_NOMBRE, p.SEG_NOMBRE, p.PRI_APELLIDO,p.SEG_APELLIDO,p.GENERO,p.FECHA_NACIMIENTO,
p.EDAD,p.TIPO_ID,p.NUMERO_ID,p.ACTIVO_INACTIVO,p.CORREO,p.TELEFONO,p.DIRECCION,d.DEPARTAMENTO,
p.FECHA_REGISTRO,e.NOM_ENCARGADO, e.PARENTESCO, e.IDENTIFICACION, e.TELEFONO as TEL_ENCARGADO
FROM tbl_encargado e, tbl_pacientes p, tbl_departamentos d
where e.COD_ENCARGADO = p.COD_ENCARGADO
and d.COD_DEPARTAMENTO = p.COD_DEPARTAMENTO;
COMMIT;
END$$


DROP PROCEDURE IF EXISTS `SP_SELECT_PACIENTE_ENCARGADO_DEPARTAMENTO2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_PACIENTE_ENCARGADO_DEPARTAMENTO2` (IN `COD_PACIENTE` INT)  BEGIN
START TRANSACTION;
SELECT p.COD_PACIENTE,p.PRI_NOMBRE, p.SEG_NOMBRE, p.PRI_APELLIDO,p.SEG_APELLIDO,p.GENERO,p.FECHA_NACIMIENTO,
p.EDAD,p.TIPO_ID,p.NUMERO_ID,p.ACTIVO_INACTIVO,p.CORREO,p.TELEFONO,p.DIRECCION,d.DEPARTAMENTO,
p.FECHA_REGISTRO,e.NOM_ENCARGADO, e.PARENTESCO, e.IDENTIFICACION, e.TELEFONO as TEL_ENCARGADO
FROM tbl_encargado e, tbl_pacientes p, tbl_departamentos d
where e.COD_ENCARGADO = p.COD_ENCARGADO
and d.COD_DEPARTAMENTO = p.COD_DEPARTAMENTO
AND P.COD_PACIENTE = COD_PACIENTE;
COMMIT;
END$$

/*UPDATE PACIENTE Y ENCARGADO*/

DROP PROCEDURE IF EXISTS `SP_UPDATE_PACIENTE_ENCARGADO`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_UPDATE_PACIENTE_ENCARGADO` (IN `COD_PACIENTE` INT(11), IN `PRI_NOMBRE` VARCHAR(30), IN `SEG_NOMBRE` VARCHAR(30), IN `PRI_APELLIDO` VARCHAR(30), IN `SEG_APELLIDO` VARCHAR(30), IN `GENERO` VARCHAR(30), IN `FECHA_NACIMIENTO` DATE, IN `EDAD` TINYINT(4), IN `TIPO_ID` VARCHAR(30), IN `NUMERO_ID` VARCHAR(30), IN `ACTIVO_INACTIVO` VARCHAR(30), IN `CORREO` VARCHAR(40), IN `TELEFONO_PAC` VARCHAR(30), IN `DIRECCION` VARCHAR(100), IN `DEPARTAMENTO` VARCHAR(30), IN `NOM_ENCARGADO` VARCHAR(30), IN `PARENTESCO` VARCHAR(30), IN `IDENTIFICACION` VARCHAR(30), IN `TELEFONO` VARCHAR(30))  BEGIN
START TRANSACTION;

SELECT @COD_ENCARGADO := COD_ENCARGADO FROM tbl_pacientes p where p.COD_PACIENTE = COD_PACIENTE;
SELECT @COD_DEPARTAMENTO := COD_DEPARTAMENTO FROM tbl_departamentos d WHERE d.DEPARTAMENTO =DEPARTAMENTO;

UPDATE tbl_pacientes p set p.PRI_NOMBRE = PRI_NOMBRE,p.SEG_NOMBRE = SEG_NOMBRE, p.PRI_APELLIDO = PRI_APELLIDO, p.SEG_APELLIDO = SEG_APELLIDO,
 p.GENERO = GENERO, p.FECHA_NACIMIENTO = FECHA_NACIMIENTO, p.EDAD = EDAD, p.TIPO_ID = TIPO_ID, p.NUMERO_ID = NUMERO_ID, p.ACTIVO_INACTIVO = ACTIVO_INACTIVO, 
 p.CORREO = CORREO, p.TELEFONO = TELEFONO_PAC, p.DIRECCION = DIRECCION, p.COD_DEPARTAMENTO = @COD_DEPARTAMENTO, p.FECHA_REGISTRO = NOW()
 WHERE p.COD_PACIENTE = COD_PACIENTE;
 
 UPDATE tbl_encargado e set e.NOM_ENCARGADO = NOM_ENCARGADO, e.PARENTESCO = PARENTESCO, 
 e.IDENTIFICACION = IDENTIFICACION, e.TELEFONO = TELEFONO
 WHERE e.COD_ENCARGADO = @COD_ENCARGADO;
 
COMMIT;
END$$

/*DELETE PACIENTE Y ENCARGADO*/

DROP PROCEDURE IF EXISTS `SP_DELETE_PACIENTE_ENCARGADO`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_DELETE_PACIENTE_ENCARGADO` (IN `COD_PACIENTE` INT(11))  
BEGIN

DELETE FROM tbl_citas where tbl_citas.COD_PACIENTE = COD_PACIENTE;
DELETE FROM tbl_consultas where tbl_consultas.COD_PACIENTE = COD_PACIENTE;
SELECT @COD_ENCARGADO :=COD_ENCARGADO FROM tbl_pacientes WHERE tbl_pacientes.COD_PACIENTE = COD_PACIENTE;
DELETE FROM tbl_pacientes where tbl_pacientes.COD_PACIENTE = COD_PACIENTE;
DELETE FROM tbl_encargado where tbl_encargado.COD_ENCARGADO = @COD_ENCARGADO;

END$$


/*PROCEDIMIENTOS ALMACENADOS CITAS*/


DELIMITER $$
DROP PROCEDURE IF EXISTS `SP_INSERT_CITA`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERT_CITA`(IN `NUMERO_ID` VARCHAR(30), IN `ASUNTO_NOMBRE` VARCHAR(20), IN `LUGAR_CLINICA` VARCHAR(30), IN `FECHA_INICIO` DATETIME, IN `FECHA_FIN` DATETIME, IN `ESTADO_CITA` VARCHAR(30))
BEGIN
START TRANSACTION;
SELECT @COD_PACIENTE := COD_PACIENTE 
FROM tbl_pacientes WHERE tbl_pacientes.NUMERO_ID=NUMERO_ID;

INSERT INTO `tbl_citas`(`COD_CITA`, `COD_PACIENTE`, `ASUNTO_NOMBRE`, `LUGAR_CLINICA`, `FECHA_INICIO`, `FECHA_FIN`, `ESTADO_CITA`, `FECHA_REGISTRO`) 
VALUES (COD_CITA,@COD_PACIENTE,ASUNTO_NOMBRE,LUGAR_CLINICA,FECHA_INICIO,FECHA_FIN,ESTADO_CITA,CURRENT_TIMESTAMP());
COMMIT;
END$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `SP_SELECT_CITA`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_CITA`(IN `COD_CITA` INT(11))
BEGIN
START TRANSACTION;
SELECT concat(p.PRI_NOMBRE, ' ', p.SEG_NOMBRE,' ',p.PRI_APELLIDO,' ',p.SEG_APELLIDO) as Nombre,p.NUMERO_ID,c.ASUNTO_NOMBRE,p.TELEFONO,c.COD_CITA,c.LUGAR_CLINICA,
c.FECHA_INICIO,c.FECHA_FIN,c.ESTADO_CITA,c.FECHA_REGISTRO
FROM tbl_pacientes p ,tbl_citas c
where c.COD_CITA = COD_CITA
and p.COD_PACIENTE = c.COD_PACIENTE;
COMMIT;
END$$
DELIMITER ;


DELIMITER $$
DROP PROCEDURE IF EXISTS `SP_SELECT_CITAS`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_CITAS`()
BEGIN
START TRANSACTION;
 SELECT  c.COD_CITA, concat(p.PRI_NOMBRE, ' ', p.SEG_NOMBRE,' ',p.PRI_APELLIDO,' ',p.SEG_APELLIDO) as NOMBRE ,p.NUMERO_ID,p.TELEFONO,c.ASUNTO_NOMBRE as ASUNTO,c.FECHA_INICIO,c.FECHA_FIN,c.ESTADO_CITA,c.LUGAR_CLINICA, c.FECHA_REGISTRO
 FROM tbl_citas c, tbl_pacientes p
 where c.COD_PACIENTE = p.COD_PACIENTE
 order by c.fecha_inicio desc;
COMMIT;
END$$
DELIMITER ;

DELIMITER $$
DROP PROCEDURE IF EXISTS `SP_SELECT_CLINICA`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_SELECT_CLINICA` ()
BEGIN
START TRANSACTION;
SELECT `COD_CLINICA`, `HORARIO_CLINICA`, `TELEFONO_CLINICA`, `UBICACION_CLI`, `RTN_CLINICA`, `RED_SOCIAL`, `LOGO_CLINICA`,`FECHA_REGISTRO`, `COD_CAI` 
FROM `tbl_clinica`; 
COMMIT;
END$$
DELIMITER ;
